error resolved

diff --git a/.github/workflows/mainPipeline.yml b/.github/workflows/mainPipeline.yml
--- a/.github/workflows/mainPipeline.yml
+++ b/.github/workflows/mainPipeline.yml
@@ -40,6 +40,7 @@ jobs:
   
   IAC_Build:
     runs-on: ubuntu-latest
+    needs: [Build_docker_Image]
     permissions: write-all
     steps:
       - name: Checkout codess
@@ -156,22 +157,42 @@ jobs:
         branch: dev-L00171125-Abhishek-DGW-132
 
 
-  SonarCloudSCan:
-   # needs: [ Build_docker_Image, IAC_Build]
+  SonarCloudScan:
     runs-on: ubuntu-latest
+ 
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3   
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
         with:
-            fetch-depth: 0
-      - name: SonarCloud Scans
-        uses: sonarsource/sonarcloud-github-action@master
+          node-version: '16'
+      - name: Install dependencies
+        run: cd WWA-backend-master && npm install
+      - name: Run Jest tests with coverage
+        run: cd WWA-backend-master && npm test -- --coverage || true
+        # Run tests with coverage, ignoring failures with '|| true'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+ 
+      - name: SonarCloud Scan
+        # uses: sonarsource/sonarcloud-github-action@master
+        uses: SonarSource/sonarcloud-github-action@master
+        # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
         env:
-           # GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
-            SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
         with:
           args: >
-              -Dsonar.organization=wwag3
-              -Dsonar.projectKey=shreyashettys202_DevOps2023-2024-Group3
+            -Dsonar.organization=jollyjerinjoy
+            -Dsonar.projectKey=jollyjerinjoy_myreactapp1
+            -Dsonar.sources=.
+            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}
+            -Dsonar.javascript.lcov.reportPaths=WWA-backend-master/coverage/lcov.info
+
             
 
   OWASP-ZAP_scan:
@@ -199,5 +220,99 @@ jobs:
           path: |
             report_html.html
             report_json.json
+
+
+  Jmeter_performance_test:
+    runs-on: windows-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up JDK
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '11'
+
+      - name: Download and install JMeter
+        run: |
+          Invoke-WebRequest -Uri 'https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.1.zip' -OutFile 'jmeter.zip'
+          Expand-Archive -Path 'jmeter.zip' -DestinationPath 'C:\tools\jmeter'
+
+      - name: Run JMeter tests
+        run: |
+          & 'C:\tools\jmeter\bin\jmeter.bat' -n -t path\to\your\testplan.jmx -l testresults.jtl
+
+  snyk_analysis:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '20'
+      - name: Install dependencies
+        run: cd WWA-backend-master && npm install
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: '17'
+          distribution: 'adopt'
+          
+# Snyk security scan step for web
+
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '20' # Adjust based on your project's Node.js version
+
+      - name: Install Snyk CLI
+        run: npm install -g snyk
+
+      - name: Snyk Security Scan
+        run: snyk test --org=shreyashettys202 --project-name='Project-Group3'
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-backend-master
+
+      - name: Snyk Security Scan Frontend
+        run: snyk test --org=shreyashettys202 --project-name='Project-Group3'
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-frontend-master
+                
+      - name: Snyk Monitor
+        run: snyk monitor --org=shreyashettys202 --project-name='Project-Group3'
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-backend-master
+
+      - name: Snyk Monitor Frontend
+        run: snyk monitor --org=shreyashettys202 --project-name='Project-Group3'
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-frontend-master
+                
+  # Snyk security scan step for Code Scanning
+
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/node@master
+        continue-on-error: true
+        with:
+          args: ./WWA-backend-master --sarif-file-output=snyk.sarif
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - name: Upload SARIF to GitHub Security Center
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: snyk.sarif
+          category: 'Snyk OpenSource Unique Category'
 
      
